logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.boot.diagnostics: trace
#    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful
  port: 9000


management:

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  health:
    livenessState: # 开启 /actuator/health/liveness
      enabled: true
    readinessState: # 开启 /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false
    tags:
      application: ${spring.application.name}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-authorization-server

  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/example_spring_authorization_server?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
  sql:
    init:
      schema-locations:
        - classpath*:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
        - classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
        - classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql
      # mode: always

  security:
    oauth2:
      client:
        provider:
          github:
            user-name-attribute: login
        registration:
          github-idp:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-name: Sign in with GitHub
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            provider: github
            scope:
            - user:email
            - read:user

