logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.boot.diagnostics: trace
#    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful
  port: 9000


management:

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
      show-details: always
    info:
      enabled: true

  health:
    livenessState: # 开启 /actuator/health/liveness
      enabled: true
    readinessState: # 开启 /actuator/health/readiness
      enabled: true

  metrics:
    enable:
      jvm: true
    use-global-registry: false

  observations:
    key-values:
      application: ${spring.application.name}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-authorization-server
  jpa:
    show-sql: true
    generate-ddl: true

  docker:
    compose:
      enabled: false

  sql:
    init:
      # mode: always
      schema-locations:
        - classpath*:org/springframework/security/oauth2/server/authorization/client/oauth2-registered-client-schema.sql
        - classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-consent-schema.sql
        - classpath*:org/springframework/security/oauth2/server/authorization/oauth2-authorization-schema.sql


  security:
    oauth2:

      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "oidc-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/oidc-client"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true

      client:
        provider:
          github:
            user-name-attribute: login
        registration:
          github-idp:
            client-id: ${OAUTH_GITHUB_CLIENT_ID}
            client-name: Sign in with GitHub
            client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
            provider: github
            scope:
            - user:email
            - read:user

