spring:
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
        web-admin-password: 123456
  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST}:3306/example_spring_authorization_server?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_USER}
    password: ${DB_MYSQL_PASSWORD}
