logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: trace
    org.springframework.security.oauth2: trace
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful

management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-authorization-server
#  main:
#    allow-bean-definition-overriding: true

app:
  oauth:
    issuer: http://127.0.0.1:8080
    private-key: classpath:jwts/rsa_private.isa
    public-key: classpath:jwts/rsa_public.isa

