logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: dev
  application:
    name: example-spring-authorization-server
app:
  oauth:
    issuer: http://localhost:8080/
    private-key: classpath:jwts/rsa_private.isa
    public-key: classpath:jwts/rsa_public.isa

